name: Quiet-code-owners
author: Drew McMillan <hello@mcmill.co.uk>
description: Have the safety of code owners without the notification headache
inputs:
  github_token:
    description: Token for the GitHub API.
    default: ${{ github.token }}
runs:
  using: node16
  main: dist/index.js
branding:
  icon: lock
  color: orange
